import Head from "next/head";
import Main from "~/components/main";
import Content from "~/components/content";
import Title from "~/components/Title";
import CornerBorders from "~/components/cornerBorders";

export default function Home() {
  return (
    <>
      <Head>
        <title>Leo Morton</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Content>
          <Title title="Leo Morton"></Title>
          <div className="dashed h-12"></div>
          <div className="relative">
            <CornerBorders />
            <h3 className="whitespace-nowrap px-[3vw] py-[2vw] font-halogenRegular text-sm font-medium leading-none text-neutral-700 sm:py-[1vw] sm:text-xl md:text-3xl">
              Project 1
            </h3>
          </div>
        </Content>
      </Main>
    </>
  );
}
