import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';
import TitleBar from '../components/TitleBar';
import ProjectSection from '../components/ProjectSection';

const professionalProjects = [
    { key: 1, name: 'Project1', imagesrc: '', description: "it's the first project" },
    { key: 2, name: 'Project2', imagesrc: '', description: "it's the second project" },
    { key: 3, name: 'Project3', imagesrc: '', description: "it's the third project" },
    { key: 4, name: 'Project4', imagesrc: '', description: "it's the fourth project" },
];

const personalProjects = [
    { key: 1, name: 'Project P 1', imagesrc: '', description: "it's the first personal project" },
    { key: 2, name: 'Project P 2', imagesrc: '', description: "it's the second personal project" },
    { key: 3, name: 'Project P 3', imagesrc: '', description: "it's the third personal project" },
    { key: 4, name: 'Project P 4', imagesrc: '', description: "it's the fourth personal project" },
    { key: 5, name: 'Project P 5', imagesrc: '', description: "it's the fifth personal project" },
    { key: 6, name: 'Project P 6', imagesrc: '', description: "it's the sixth personal project" },
];

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <TitleBar />
                <ProjectSection sectionTitle={'Professional Projects'} projects={professionalProjects} />
            </main>

            <footer className={styles.footer}></footer>
        </div>
    );
}
